namespace Branding.DynamicComponents.ResolveByContract
{
    public record ServiceComponentPlacementContract(ServicePlacementName ServicePlaceHolderName, ServiceDynamicComponentParameterRequirements ComponentParameterRequirements);
}
